name: Origins-Magic
version: 1.0.3
main: com.starshootercity.magicorigins.OriginsMagic
description: Origins-Reborn addon to add origins with magical abilities
api-version: '1.19'
author: cometcake575

depend:
  - Origins-Reborn
